"""
Django settings for serverless project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gf^!o2#syugc_a0mveagfo5xzd1fp0()k58n-2cxv%zlbk*d*h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS =  os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Serverless Function Endpoint List
SERVERLESS_SAGEMAKER_ENDPOINT = os.environ.get('SERVERLESS_SAGEMAKER_ENDPOINT', 'localhost')

TF_RCNN_ENDPOINT = os.environ.get('TF_RCNN_ENDPOINT', SERVERLESS_SAGEMAKER_ENDPOINT)
TF_RCNN_NAME = os.environ.get('TF_RCNN_NAME', 'tfFastrcnnContainer')

PTH_RCNN_ENDPOINT = os.environ.get('PTH_RCNN_ENDPOINT', SERVERLESS_SAGEMAKER_ENDPOINT)
PTH_RCNN_NAME = os.environ.get('PTH_RCNN_NAME', 'pthFastrcnnContainer')

PTH_IOG_ENDPOINT = os.environ.get('PTH_IOG_ENDPOINT', SERVERLESS_SAGEMAKER_ENDPOINT)
PTH_IOG_NAME = os.environ.get('PTH_IOG_NAME', 'pthIogContainer')

PTH_SIAMMASK_ENDPOINT = os.environ.get('PTH_SIAMMASK_ENDPOINT', SERVERLESS_SAGEMAKER_ENDPOINT)
PTH_SIAMMASK_NAME = os.environ.get('PTH_SIAMMASK_NAME', 'pthSimmaskContainer')

OPENVINO_IDENTIFICATION_ENDPOINT = os.environ.get('OPENVINO_IDENTIFICATION_ENDPOINT', SERVERLESS_SAGEMAKER_ENDPOINT)
OPENVINO_IDENTIFICATION_NAME = os.environ.get('OPENVINO_IDENTIFICATION_NAME', 'openvinoIdentificationContainer')

DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = None   # this django check disabled
LOCAL_LOAD_MAX_FILES_COUNT = 500
LOCAL_LOAD_MAX_FILES_SIZE = 512 * 1024 * 1024  # 512 MB


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'functions.apps.FunctionsConfig',
]

MIDDLEWARE = [
    #'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'serverless.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'serverless.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    ]
}
